version = 0.2
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "xxxxxxxxxxxxxxxx-user-project-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ewqp4pc3crvm"
s3_prefix = "xxxxxxxxxxxxxxxx"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "xxxxxxxxxxxxxxxx-user-project"
s3_bucket = "xxxxxxxxxxxxxxxx"
s3_prefix = "xxxxxxxxxxxxxxxx"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
