AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: xxxxxxxxxxxxxxxx

Globals:
  Function:
    Environment:
      Variables:
        DB_HOST: xxxxxxxxxxxxxxxx
        DB_USER: xxxxxxxxxxxxxxxx
        DB_PASSWORD: xxxxxxxxxxxxxxxx
        DB_NAME: xxxxxxxxxxxxxxxx
        AWS_REGION_NAME: xxxxxxxxxxxxxxxx
        COGNITO_POOL_id: xxxxxxxxxxxxxxxx
        COGNITO_APP_CLIENT_ID: xxxxxxxxxxxxxxxx

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "xxxxxxxxxxxxxxxx"
      Handler: app.handler
      Runtime: python3.8
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'